name: Linting, Style, Error Checking

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install
        run: brew install luacheck
      - name: Lint
        run: make lint

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install
        run: brew install stylua
      - name: Check
        run: make format-check

  lsp-check:
    name: LSP Error Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install
        run: brew install lua-language-server
      - name: Check
        run: make lsp-check

  help-check:
    name: Help Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: cargo install lemmy-help --features=cli
      - name: Check
        run: make help-check
